apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8qpm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8qpm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8qpm
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8qpm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8qpm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hncr-tenant/rhtap-demo-app/hacbs-test-project-8qpm@sha256:6d17545d47e3608822f79050abfa0357fb04a1dc2bf5e549fe5d580dcd2c6704
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
